config/routes.rb
Rails.application.routes.draw do
  resources :desenvolvedores
  resources :clientes
  resources :produtos
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  belongs_to :Produto
end

app/models/desenvolvedore.rb
class Desenvolvedore < ApplicationRecord
  belongs_to :Produto
end

app/models/produto.rb
class Produto < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: %i[ show edit update destroy ]

  # GET /clientes or /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1 or /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes or /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to cliente_url(@cliente), notice: "Cliente was successfully created." }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1 or /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to cliente_url(@cliente), notice: "Cliente was successfully updated." }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1 or /clientes/1.json
  def destroy
    @cliente.destroy!

    respond_to do |format|
      format.html { redirect_to clientes_url, notice: "Cliente was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cliente_params
      params.require(:cliente).permit(:cnpj, :nome, :endereco, :telefone, :email, :Produto_id)
    end
end

app/controllers/desenvolvedores_controller.rb
class DesenvolvedoresController < ApplicationController
  before_action :set_desenvolvedore, only: %i[ show edit update destroy ]

  # GET /desenvolvedores or /desenvolvedores.json
  def index
    @desenvolvedores = Desenvolvedore.all
  end

  # GET /desenvolvedores/1 or /desenvolvedores/1.json
  def show
  end

  # GET /desenvolvedores/new
  def new
    @desenvolvedore = Desenvolvedore.new
  end

  # GET /desenvolvedores/1/edit
  def edit
  end

  # POST /desenvolvedores or /desenvolvedores.json
  def create
    @desenvolvedore = Desenvolvedore.new(desenvolvedore_params)

    respond_to do |format|
      if @desenvolvedore.save
        format.html { redirect_to desenvolvedore_url(@desenvolvedore), notice: "Desenvolvedore was successfully created." }
        format.json { render :show, status: :created, location: @desenvolvedore }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @desenvolvedore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /desenvolvedores/1 or /desenvolvedores/1.json
  def update
    respond_to do |format|
      if @desenvolvedore.update(desenvolvedore_params)
        format.html { redirect_to desenvolvedore_url(@desenvolvedore), notice: "Desenvolvedore was successfully updated." }
        format.json { render :show, status: :ok, location: @desenvolvedore }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @desenvolvedore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /desenvolvedores/1 or /desenvolvedores/1.json
  def destroy
    @desenvolvedore.destroy!

    respond_to do |format|
      format.html { redirect_to desenvolvedores_url, notice: "Desenvolvedore was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_desenvolvedore
      @desenvolvedore = Desenvolvedore.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def desenvolvedore_params
      params.require(:desenvolvedore).permit(:cpf, :nome, :funcao, :telefone, :salario, :endereco, :Produto_id)
    end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: %i[ show edit update destroy ]

  # GET /produtos or /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1 or /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos or /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to produto_url(@produto), notice: "Produto was successfully created." }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1 or /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to produto_url(@produto), notice: "Produto was successfully updated." }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1 or /produtos/1.json
  def destroy
    @produto.destroy!

    respond_to do |format|
      format.html { redirect_to produtos_url, notice: "Produto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def produto_params
      params.require(:produto).permit(:serial, :nome, :descricao, :preco, :versao)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/desenvolvedores_helper.rb
module DesenvolvedoresHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/clientes/_cliente.html.erb
<div id="<%= dom_id cliente %>">
  <p>
    <strong>Cnpj:</strong>
    <%= cliente.cnpj %>
  </p>

  <p>
    <strong>Nome:</strong>
    <%= cliente.nome %>
  </p>

  <p>
    <strong>Endereco:</strong>
    <%= cliente.endereco %>
  </p>

  <p>
    <strong>Telefone:</strong>
    <%= cliente.telefone %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= cliente.email %>
  </p>

  <p>
    <strong>Produto:</strong>
    <%= cliente.Produto_id %>
  </p>

</div>

app/views/clientes/_form.html.erb
<%= form_with(model: cliente) do |form| %>
  <% if cliente.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
        <% cliente.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :cnpj, style: "display: block" %>
    <%= form.text_field :cnpj %>
  </div>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :endereco, style: "display: block" %>
    <%= form.text_field :endereco %>
  </div>

  <div>
    <%= form.label :telefone, style: "display: block" %>
    <%= form.text_field :telefone %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :Produto_id, style: "display: block" %>
    <%= form.text_field :Produto_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editing cliente</h1>

<%= render "form", cliente: @cliente %>

<br>

<div>
  <%= link_to "Mostrar este cliente", @cliente %> |
  <%= link_to "voltar para clientes", clientes_path %>
</div>

app/views/clientes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Clientes</h1>

<div id="clientes">
  <% @clientes.each do |cliente| %>
    <%= render cliente %>
    <p>
      <%= link_to "Mostrar este cliente", cliente %>
    </p>
  <% end %>
</div>

<%= link_to "Novo cliente", new_cliente_path %>

app/views/clientes/new.html.erb
<h1>Novo Cliente</h1>

<%= render "form", cliente: @cliente %>

<br>

<div>
  <%= link_to "Voltar para clientes", clientes_path %>
</div>

app/views/clientes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @cliente %>

<div>
  <%= link_to "Editar este cliente", edit_cliente_path(@cliente) %> |
  <%= link_to "Voltar para clientes", clientes_path %>

  <%= button_to "Remover este cliente", @cliente, method: :delete %>
</div>

app/views/desenvolvedores/_desenvolvedore.html.erb
<div id="<%= dom_id desenvolvedore %>">
  <p>
    <strong>Cpf:</strong>
    <%= desenvolvedore.cpf %>
  </p>

  <p>
    <strong>Nome:</strong>
    <%= desenvolvedore.nome %>
  </p>

  <p>
    <strong>Funcao:</strong>
    <%= desenvolvedore.funcao %>
  </p>

  <p>
    <strong>Telefone:</strong>
    <%= desenvolvedore.telefone %>
  </p>

  <p>
    <strong>Salario:</strong>
    <%= desenvolvedore.salario %>
  </p>

  <p>
    <strong>Endereco:</strong>
    <%= desenvolvedore.endereco %>
  </p>

  <p>
    <strong>Produto:</strong>
    <%= desenvolvedore.Produto_id %>
  </p>

</div>

app/views/desenvolvedores/_form.html.erb
<%= form_with(model: desenvolvedore) do |form| %>
  <% if desenvolvedore.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(desenvolvedore.errors.count, "error") %> prohibited this desenvolvedore from being saved:</h2>

      <ul>
        <% desenvolvedore.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :cpf, style: "display: block" %>
    <%= form.text_field :cpf %>
  </div>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :funcao, style: "display: block" %>
    <%= form.text_field :funcao %>
  </div>

  <div>
    <%= form.label :telefone, style: "display: block" %>
    <%= form.text_field :telefone %>
  </div>

  <div>
    <%= form.label :salario, style: "display: block" %>
    <%= form.text_field :salario %>
  </div>

  <div>
    <%= form.label :endereco, style: "display: block" %>
    <%= form.text_field :endereco %>
  </div>

  <div>
    <%= form.label :Produto_id, style: "display: block" %>
    <%= form.text_field :Produto_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/desenvolvedores/edit.html.erb
<h1>Editing desenvolvedore</h1>

<%= render "form", desenvolvedore: @desenvolvedore %>

<br>

<div>
  <%= link_to "Mostrar este desenvolvedor", @desenvolvedore %> |
  <%= link_to "Voltar para desenvolvedores", desenvolvedores_path %>
</div>

app/views/desenvolvedores/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Desenvolvedores</h1>

<div id="desenvolvedores">
  <% @desenvolvedores.each do |desenvolvedore| %>
    <%= render desenvolvedore %>
    <p>
      <%= link_to "Mostrar este desenvolvedor", desenvolvedore %>
    </p>
  <% end %>
</div>

<%= link_to "Novo desenvolvedor", new_desenvolvedore_path %>

app/views/desenvolvedores/new.html.erb
<h1>New desenvolvedore</h1>

<%= render "form", desenvolvedore: @desenvolvedore %>

<br>

<div>
  <%= link_to "Voltar para desenvolvedores", desenvolvedores_path %>
</div>

app/views/desenvolvedores/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @desenvolvedore %>

<div>
  <%= link_to "Editar este desenvolvedor", edit_desenvolvedore_path(@desenvolvedore) %> |
  <%= link_to "Voltar para desenvolvedores", desenvolvedores_path %>

  <%= button_to "Remover este desenvolvedor", @desenvolvedore, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aplication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/produtos/_form.html.erb
<%= form_with(model: produto) do |form| %>
  <% if produto.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
        <% produto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :serial, style: "display: block" %>
    <%= form.text_field :serial %>
  </div>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :descricao, style: "display: block" %>
    <%= form.text_field :descricao %>
  </div>

  <div>
    <%= form.label :preco, style: "display: block" %>
    <%= form.text_field :preco %>
  </div>

  <div>
    <%= form.label :versao, style: "display: block" %>
    <%= form.text_field :versao %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/produtos/_produto.html.erb
<div id="<%= dom_id produto %>">
  <p>
    <strong>Serial:</strong>
    <%= produto.serial %>
  </p>

  <p>
    <strong>Nome:</strong>
    <%= produto.nome %>
  </p>

  <p>
    <strong>Descricao:</strong>
    <%= produto.descricao %>
  </p>

  <p>
    <strong>Preco:</strong>
    <%= produto.preco %>
  </p>

  <p>
    <strong>Versao:</strong>
    <%= produto.versao %>
  </p>

</div>

app/views/produtos/edit.html.erb
<h1>Editing produto</h1>

<%= render "form", produto: @produto %>

<br>

<div>
  <%= link_to "Mostrar este produto", @produto %> |
  <%= link_to "Voltar para produtos", produtos_path %>
</div>

app/views/produtos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Produtos</h1>

<div id="produtos">
  <% @produtos.each do |produto| %>
    <%= render produto %>
    <p>
      <%= link_to "Mostrar este produto", produto %>
    </p>
  <% end %>
</div>

<%= link_to "Novo produto", new_produto_path %>

app/views/produtos/new.html.erb
<h1>New produto</h1>

<%= render "form", produto: @produto %>

<br>

<div>
  <%= link_to "Voltar para produtos", produtos_path %>
</div>

app/views/produtos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @produto %>

<div>
  <%= link_to "Editar este produto", edit_produto_path(@produto) %> |
  <%= link_to "Voltar para produtos", produtos_path %>

  <%= button_to "Remover este produto", @produto, method: :delete %>
</div>